spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: user
    password: user
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect